### ISSUE TITLE
TRC20-Contract-Template/Token.sol

### ISSUE THREAD

**Issue by USCOIN7** [TRON-Developer-Hub/TRC20-Contract-Template#67]
TRC20-Contract-Template/Token.sol

**Comment by 34adem** [comment]
TUvFipnXP8B4QfQYcZcwzELPrytxKrbdyd

**Comment by Erkansukgen** [comment]
Hello

**Comment by Erkansukgen** [comment]
> TZGVxqavTxZE5FJxVfZgrmxwP3YFAQvrAS

Open

**Comment by Erkansukgen** [comment]
> TZGVxqavTxZE5FJxVfZgrmxwP3YFAQvrAS
